<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GatewayPulse.PowerMonitoring\GatewayPulse.PowerMonitoring.csproj" />
    <ProjectReference Include="..\GatewayPulse.RfMonitoring\GatewayPulse.RfMonitoring.csproj" />
    <ProjectReference Include="..\GatewayPulse.VictronMonitor\GatewayPulse.VictronMonitor.csproj" />
    <ProjectReference Include="..\GatewayPulse.Lp100Monitor\GatewayPulse.Lp100Monitor.csproj" />
    <ProjectReference Include="..\GatewayPulse.Service\GatewayPulse.Service.csproj" />
  </ItemGroup>
</Project>
